### ISSUE TITLE
Time estimate empty

### ISSUE THREAD

**Issue by shaarkys** [jonkristian/no.jonkristian.octoprint#11] opened 2021-03-31 19:03 UTC
Hi,
so far I'm very happy with your Octoprint Homey app - just a small issue - Time estimate never appears, is it a bug ?
Thank you

![obrazek](https://user-images.githubusercontent.com/14859895/113197069-845cef00-9264-11eb-8c89-a67f591b439e.png)
![obrazek](https://user-images.githubusercontent.com/14859895/113197075-8757df80-9264-11eb-8199-0e583c3ddf42.png)

**Comment by jonkristian** [comment] 2021-04-01 08:51
Thanks I will take a look. Could you send a diagnostics report while you are seeing this?

**Comment by shaarkys** [comment] 2021-04-01 11:58
Sure, here you go  - e061328a-2493-4eee-9eae-d073838833df
I just noticed that the time is also not available right in the beginning in Octoprint, it appears later.

**Comment by jonkristian** [comment] 2021-04-02 13:33
Time? Are you saying time estimate gets the value, or are you talking about print time sensor?

Not all values are available upon first request. Especially the estimate, do you get an estimate after a while or?

Btw, your diagnostics doesn't show anything out of the ordinary. I can see it's not getting contact with the octoprint server in the beginning, but guessing you do get values in so those are probably safe to ignore (old logs).

**Comment by shaarkys** [comment] 2021-04-02 18:30
> Time? Are you saying time estimate gets the value, or are you talking about print time sensor?

Simply in your app, the value "Time Estimate" is always empty, while in Octoprint I do see Time estimation. Not sure if this is desired or not :-) No big deal, yet I guess this value shall not be empty all the time, or ?

**Comment by jonkristian** [comment] 2021-04-08 21:08
That is strange, do you run any special plugins? Could you please try the following from a terminal while printing and paste the output here? ... replacing token and ip with your own.

`curl -X 'GET' -H 'Content-Type: application/json' -H 'Authorization: Bearer YOUR-TOKEN' http://your-ip/api/job`

Results should confirm if print time is returned by the api or not.

**Comment by shaarkys** [comment] 2021-04-09 16:00
Sure...here is the beginning of the print (also Octoprint do not show estimation / time left)
`{"job":{"averagePrintTime":null,"estimatedPrintTime":null,"filament":null,"file":{"date":1617983263,"display":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","name":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","origin":"local","path":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","size":5383789},"lastPrintTime":null,"user":"_api"},"progress":{"completion":0.017998476537620624,"filepos":969,"printTime":0,"printTimeLeft":null,"printTimeLeftOrigin":"linear"},"state":"Printing"}`

And here after a while : 
`{"job":{"averagePrintTime":null,"estimatedPrintTime":null,"filament":null,"file":{"date":1617983263,"display":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","name":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","origin":"local","path":"AQARA-Stand_0.1mm_PETG_MK3S_1h15m.gcode","size":5383789},"lastPrintTime":null,"user":"_api"},"progress":{"completion":5.81980460229775,"filepos":313326,"printTime":747,"printTimeLeft":8067,"printTimeLeftOrigin":"estimate"},"state":"Printing"}`

**Comment by jonkristian** [comment] 2021-04-10 10:36
Hmm, I can see you clearly get values back in your second query, that's normal for octoprint since it takes some time for it to calculate. There is nothing special going on while querying this particular value either, it's just the same as the other time values we get back so that has me stumped. If you haven't already, could you also please try and remove the device and re-install the app, just to make sure?

What version of octoprint are you running? I will do some testing and see if I can reproduce this.

Thanks for reporting!

**Comment by shaarkys** [comment] 2021-04-11 19:12
>  If you haven't already, could you also please try and remove the device and re-install the app, just to make sure?

Just tested, unfortunately no difference even after removal and adding it back again.

> What version of octoprint are you running? I will do some testing and see if I can reproduce this.

I'm on version 1.6.0rc1, but it was the same even on previous version.

It's not big deal, rest works really great ! ;-)

**Comment by shaarkys** [comment] 2021-04-12 08:05
...when running from console, not sure if it's relevant. Even I installed it and got rid of that error, it still doesn't  show Time estimate.

`─────────────── Logging stdout & stderr ───────────────
[log] 2021-04-12 07:46:55 [OctoPrint] Octoprint has been initialized.
[err] 2021-04-12 07:46:55 [ManagerDrivers] Error: Cannot find module 'node-fetch'
Require stack:
- /lib/octoprint.js
- /drivers/octoprint/driver.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/homey.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.homeyRequire [as require] (/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js:12:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/lib/octoprint.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/lib/octoprint.js',
    '/drivers/octoprint/driver.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/homey.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap.js'
  ]
}`

**Comment by jonkristian** [comment] 2021-04-12 08:21
If you cloned the repo and tried to install, you shoul run `npm install` first, because it requires node-fetch as a dependency.

**Comment by shaarkys** [comment] 2021-04-12 08:29
Thanks - anyway, no error at all on "printTimeLeft" in the console... quite interesting considering you are using the same "fetch methods" (sorry for term, I'm not developer)...

**Comment by jonkristian** [comment] 2021-04-12 09:03
Yes, it's really strange ... Did you also try develop branch or vice-versa? just do a git checkout develop inside the folder.

**Comment by shaarkys** [comment] 2021-04-17 20:14
Hm, so I have uninstalled _Printer Time Genius_ plugin and installed instead _Slicer Print Time Estimator_. Unfortunately in the meantime I have also upgraded to 1.6.0rc2. But what is important, **Time Estimate** works now ;-) 

`{"job":{"averagePrintTime":null,"estimatedPrintTime":2160.0,"filament":{"tool0":{"length":1574.7519200001195,"volume":3.7877222514350164}},"file":{"date":1618689791,"display":"Strawberry_support_d21_0.2mm_PETG_MK3S_36m.gcode","name":"Strawberry_support_d21_0.2mm_PETG_MK3S_36m.gcode","origin":"local","path":"Strawberry_support_d21_0.2mm_PETG_MK3S_36m.gcode","size":1187074},"lastPrintTime":null,"user":"_api"},"progress":{"completion":0.08162928343136149,"filepos":969,"printTime":0,"printTimeLeft":2160,"printTimeLeftOrigin":"slicerestimator"},"state":"Printing"}`

**Comment by jonkristian** [comment] 2021-04-19 09:14
Awesome, so everything is working now? I'll go ahead and close this, feel free to re-open if the issue still occurs.

**Closed as completed by jonkristian** 2021-04-19 09:14 UTC
